# Generated by Django 4.2.9 on 2024-03-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantiry',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
