# Generated by Django 4.2.9 on 2024-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_review_can_review_book_can_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='can_review',
            field=models.BooleanField(default=False),
        ),
    ]
