# Generated by Django 4.2.9 on 2024-04-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='coustomer',
            new_name='user',
        ),
    ]
