# Generated by Django 4.2.9 on 2024-05-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_rename_coustomer_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='book/images/'),
        ),
    ]
