# Generated by Django 4.2.9 on 2024-03-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
