# Generated by Django 4.2.9 on 2024-03-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0002_alter_borrowing_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
