# Generated by Django 4.2.9 on 2024-03-31 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('borrow_book', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='user',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='coustomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.coustomer'),
        ),
    ]
