# Generated by Django 4.2.9 on 2024-03-31 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_quantiry'),
        ('accounts', '0001_initial'),
        ('borrow_book', '0005_remove_borrowing_user_borrowing_coustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(to='book.book')),
                ('coustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coustomer')),
            ],
        ),
    ]
