# Generated by Django 4.2.9 on 2024-04-14 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrow_book', '0007_remove_wishlist_books_remove_wishlist_coustomer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='coustomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
